Settings Dialog Backend
iTNTPiston/celer pull request #78
Opened 2023-01-11 08:55 UTC by ChowdaaCollege

2023-01-11 09:00 UTC, iTNTPiston commented
Why is the workflow not running, hmm

2023-01-11 09:02 UTC, iTNTPiston commented
I think the workflow is not triggered because your commit is not verified.

2023-01-11 09:16 UTC, iTNTPiston requested changes
Please fix the line endings with `just lintpy -f` so the diff is displayed properly

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/core/context/SettingContext.ts
> +	enableSubsplits: boolean
Why are you deleting the existing type declaration and using `typeof`? Let's not overuse `typeof` to make the compiler happy. You won't need to change this code if you update the types `MapDisplayMode`, `Theme`, etc to your new system

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/core/context/SettingContext.ts
> +		mapDisplay: getNextMap(stored.mapDisplay.name),
Why are we getting the next theme after loading? This doesn't seem right. If it's intentional please put a comment explaining why

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/core/engine/engine.ts
> +	public setSplitSetting(splitSetting: typeof defaultSplitSetting){
See my other comment about `typeof`

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/core/settings/MapDisplayMode.ts
> +};
Wait.. now I'm really confused. The function is `getNextMap` but what you are doing is essentially `MapDisplayModes[map]` Again if this is intentionally please explain in a comment.

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/core/settings/Theme.ts
> +};
See my other comment at `getNextMap`

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/ui/styles/StyleEngine.ts
>  		let mainCss = "";
See my other comment about `typeof`, same below

2023-01-13 00:55 UTC, iTNTPiston commented on packages/celer-web-app/src/ui/frames/AppFrame.tsx
> +								});
Can we use `immer` for manipulating immutable objects? https://immerjs.github.io/immer/

2023-01-18 23:32 UTC, iTNTPiston requested changes

2023-01-18 23:32 UTC, iTNTPiston commented on packages/celer-web-app/src/ui/frames/AppFrame.tsx
> +										produce(setting, (draft) => {
You don't need to nest `produce` with `immer`. see https://immerjs.github.io/immer/update-patterns/#nested-data-structures

2023-01-18 23:33 UTC, iTNTPiston commented
What testing have you done to make sure the features work as expected? (manual/automated?, etc)

2023-01-19 20:38 UTC, ChowdaaCollege commented
> What testing have you done to make sure the features work as expected? (manual/automated?, etc)

For each setting, I manually toggled them to make sure both that local storage was being updated after each change and that all the changes were reflected on the screen. Every setting is saved correctly in local storage and is reflected on the screen with both values of the toggle.

2023-01-19 21:02 UTC, iTNTPiston approved these changes

2023-01-20 05:45 UTC, merged