initial attempt at color coding document
iTNTPiston/celer pull request #87
Opened 2023-03-29 07:36 UTC by ChowdaaCollege

2023-03-29 16:47 UTC, iTNTPiston requested changes

2023-03-29 16:57 UTC, ChowdaaCollege commented on packages/celer-web-app/src/core/engine/RouteDocLine.ts
mapLineColor is not always defined for every DocLineTextComponent so I need another variable which will always be defined.

2023-03-29 17:00 UTC, iTNTPiston commented on packages/celer-web-app/src/core/engine/RouteDocLine.ts
I think you can make the Engine (not MapEngine) to always define mapLineColor? Like pulling it from previous line if it doesn't exist, similar to the coordinates

2023-04-07 08:02 UTC, iTNTPiston approved these changes

2023-04-07 16:37 UTC, merged